language: en-in
pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: components.RegexEntityExtractor.RegexEntityExtractor
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: "CRFEntityExtractor"
- name: DIETClassifier
  entity_recognition: False
  epochs: 250
  tensorboard_log_directory: tensorboard_logs
  tensorboard_log_level: epoch
  random_seed: 42
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100
policies:
- name: TEDPolicy
  epochs: 30
  hidden_layer_sizes:
    dialogue:
    - 128
    labels:
    - 128
  augmentation_factor: 25
  batch_size:
  - 32
  - 128
  random_seed: 42
  embedding_dimension: 20
  tensorboard_log_directory: tensorboard_logs
  featurizer:
  - name: MaxHistoryTrackerFeaturizer
    max_history: 10
    state_featurizer:
    - name: BinarySingleStateFeaturizer
  validation_split: 0.15
- name: AugmentedMemoizationPolicy
  max_history: 10
- name: MappingPolicy
- name: FallbackPolicy
  nlu_threshold: 0.6
  ambiguity_threshold: 0.1
  core_threshold: 0.5
  fallback_action_name: action_default_fallback
- name: FormPolicy